### ISSUE TITLE
Empty src or href

### ISSUE THREAD

**Issue by ivanslater** [kasparsd/minit#101]
Yslow is reporting error on minit-js.php -> minit-async-scripts add function. You can't leave src property empty, so a simple IF solve this issue:

add = function( url, id ) {
					js = document.createElement('script');
					js.type = 'text/javascript';
					**if (url != '') js.src = url;**
					js.async = false;
					js.id = id;
					fjs.parentNode.insertBefore(js, fjs);
				};

**Comment by kasparsd** [comment]
@ivanslater An external script shouldn't have a missing URL. Can you maybe exclude that script?

**Comment by ivanslater** [comment]
The problem is with your script:

add( "", "async-script-jquery" )

you are adding the empty src.

got it?

**Comment by kasparsd** [comment]
@ivanslater `jquery` is a container script which is being excluded here https://github.com/kasparsd/minit/blob/master/include/minit-js.php#L82-L95

**Comment by szepeviktor** [comment]
See https://github.com/kasparsd/minit/wiki/Minit-Action-and-Filter-Hooks#minit-exclude-cssjs

**Comment by ivanslater** [comment]
Great! Where I set hooks? Function.php ?

**Comment by szepeviktor** [comment]
It depends. Personally I prefer an MU plugin.
