### ISSUE TITLE
Exclude 'jquery' container script

### ISSUE THREAD

**Issue by szepeviktor** [kasparsd/minit#103]
Could we include this again in the helper - modified with jquery?
Talked about in #101

```php
// Exclude handles that are known to cause problems
add_filter( 'minit-exclude-js', 'minit_exclude_defaults' );

function minit_exclude_defaults( $handles ) {

    $exclude = array(
        'jquery',
    );

    return array_merge( $exclude, $handles );

}
```

**Comment by piihuynh** [comment]
Yes.
'jquery-core' works for me

**Comment by kasparsd** [comment]
This appears to have been fixed here:

https://github.com/kasparsd/minit/blob/7849b353b096fe89dad4e8f2d949f82ddd3e99ba/src/minit-assets.php#L110
