### ISSUE TITLE
Publish on WordPress plugins directory

### ISSUE THREAD

**Issue by strarsis** [kasparsd/minit#105]
Would it be helpful if this plugin is also published on the WordPress plugins directory?

**Comment by szepeviktor** [comment]
I secretly tell you this plugin may be for *experts only*.
Maybe I am wrong.

**Comment by kasparsd** [comment]
@strarsis This plugin works only with themes and plugins which correctly enqueue scripts which isn't the case with the majority of themes and plugins on the WP.org, and I personally don't have the time to deal with the support requests.
