### ISSUE TITLE
Move JS/CSS to foot of page

### ISSUE THREAD

**Issue by strarsis** [kasparsd/minit#109]
It would be great if minit offers an option (or a sub-plugin/hook that can be used in such?) to move the JS/CSS to the foot/bottom of a page/theme.

**Comment by kasparsd** [comment]
@strarsis This should be happening by default:

https://github.com/kasparsd/minit/blob/814483d0bd3cf06878a03aa66d0dd3f9a6b98347/include/minit-js.php#L51
