### ISSUE TITLE
[off] As simple as minit CDN plugin

### ISSUE THREAD

**Issue by szepeviktor** [kasparsd/minit#110]
Hello!

I am trying to develop a CDN plugin that is as simple and lean as minit.
It would process only WordPress core output - would not rewrite printed scripts, printed styles, non-content images etc.

https://github.com/szepeviktor/tiny-cdn/blob/master/tiny-cdn.php
Anyone here to contribute?

**Comment by kasparsd** [comment]
Closing as not directly related to the Minit plugin. Feel free to link to it from a Wiki page.

**Comment by szepeviktor** [comment]
And it is already published https://wordpress.org/plugins/tiny-cdn/
