### ISSUE TITLE
How do I unistall the plugin 

### ISSUE THREAD

**Issue by MarcusFuto** [kasparsd/minit#113]
Hello, 

Is there anything particular I have to think about when unistalling? 

I see that some things are not working after install and when uninstalling things are still the same. 

It is visual composer that has gone wild. It seems to not be able to display the different sections within VC and instead has put all rows and content into a single text box.

**Comment by kasparsd** [comment]
You could delete all the left-over files from `wp-content/uploads/minit` (including the directory). However, disabling the plugin will also stop it from doing anything.
