### ISSUE TITLE
Include in theme instead of plugin

### ISSUE THREAD

**Issue by troytempleman** [kasparsd/minit#117]
This is great but is there a way to have it in a theme instead of a plugin? I've tried including it but it doesn't work. Does it only work upon plugin activation?

**Comment by troytempleman** [comment]
The answer is to change line 21 in `minit.php:`

`add_action( 'plugins_loaded', array( 'Minit_Plugin', 'instance' ) );`

to:

`add_action( 'after_setup_theme', array( 'Minit_Plugin', 'instance' ) );`

**Comment by kasparsd** [comment]
@troytempleman Correct. Or you can call `Minit_Plugin::instance()` directly from your theme after you've included the `minit.php` file.
