### ISSUE TITLE
Why 2 CSS files added?

### ISSUE THREAD

**Issue by thatryan** [kasparsd/minit#15]
Thanks for the great plugin, found this via @bjornjohansen :+1: 

First time trying it out, and wondering why I am getting two CSS file generated and added. One in the head which appears to just be a copy of my normal theme style included, but renamed with minit data. The second stylesheet is included at bottom of the page in footer, and appears to be the concatenation of plugins styles.

Edit: Actually, just noticed it does not appear to be concatenating files, just changing their names. You can see a stack of CSS links in the screenshot here...

Thoughts?
![2014-06-19 at 11 44 am](https://cloud.githubusercontent.com/assets/26583/3331955/df3f4b4a-f7e1-11e3-9bd5-b46b0ddc6420.png)

**Comment by isaumya** [comment]
Well how does this plugin behave with WP Super cache?

**Comment by kasparsd** [comment]
Should be fixed in version 1.3.0.
