### ISSUE TITLE
Feature request: an easier way to purge cache

### ISSUE THREAD

**Issue by schilke** [kasparsd/minit#34]
This would save minutes (if not hours) - pretty hard to - go to plugins / scroll to minit / hit purge - all the time. Perhaps something like W3TC with integration into admin menu and toolbar.

Or - as an alternative a possibility to use a filter like you did with 'minit-cache-purged' (I guess I'd like that even more...)

**Comment by kasparsd** [comment]
You can already do that by updating the `minit_cache_ver` option value whenever necessary. Here is an example:

	add_action( 'init', 'minit_cache_bump_init' );

	function minit_cache_bump_init() {

	    // Bump the version number during these action calls
	    $purge_actions = array(
	        'clean_post_cache',
	        'edit_term',
	        'publish_post',
	        'comment_post',
	        'delete_comment',
	        'edit_comment',
	        'delete_post',
	        'edit_post',
	        'wp_update_nav_menu',
	        'activated_plugin',
	        'deactivated_plugin',
	        'wp_maybe_auto_update'
	    );

	    foreach ( $purge_actions as $action ) {
	        add_action( $action, 'minit_cache_bump' );
	    }

	}

	function minit_cache_bump() {
	    update_option( 'minit_cache_ver', time() );
	}

**Comment by schilke** [comment]
Straightforward & simple - exactly what I was after (and didn't find out myself...) :+1: 
Thanks a lot @kasparsd ! And a Happy New Year BTW :)
