### ISSUE TITLE
Feature request: An option to turn off combining javascript 

### ISSUE THREAD

**Issue by nadeem-khan** [kasparsd/minit#35]
Due to various ad networks related scripts and external js sometimes some sites break due to combining js files. There should be an option to turn off combining javascript and also an option to do the same for css files.

**Comment by kasparsd** [comment]
You can set Minit to ignore all JS by removing the `init_minit_js` from the `print_scripts_array` filter during the `plugins_loaded` action, like so:

	add_action( 'plugins_loaded', 'minit_skip_all_js' );

	function minit_skip_all_js() {
		
		remove_filter( 'print_scripts_array', array( Minit::instance(), init_minit_js ) );

	}
