### ISSUE TITLE
Combining js not working

### ISSUE THREAD

**Issue by santo007** [kasparsd/minit#36]
I have tested the plugin it doesnot combining js and css files instead loading them through asnyc attribute.How to fix this.I also cleared cache while viewing the source

**Comment by kasparsd** [comment]
Minit doesn't add the async attribute to JS links since WordPress core doesn't provide a simple way of doing it. The only option is to use output buffering and search/replace which is unreliable.

**Comment by santo007** [comment]
but combining is not working is there any demo or proof

**Comment by kasparsd** [comment]
It is working. For example, have a look at [my blog](http://kaspars.net/).

Do you have an example where Minit doens't work?

**Comment by santo007** [comment]
Here is my <a href="http://www.blogging-g.com">My Blog</a>.You can see that .js files are not combined by using source

**Comment by kasparsd** [comment]
Looks like you are already running some kind of tool or service that optimizes the HTML and asset delivery (judging by the removed empty spaces in HTML). I also noticed that the HTML is served by Cloudflare which might be doing some of the optimization.

Unfortunately I am unable to provide support for each particular implementation.

**Comment by santo007** [comment]
i am using w3tc plugin.Is there any problem by using it

**Comment by santo007** [comment]
also i have switched off all boosting performances done by cloudflare for my blog.

**Comment by santo007** [comment]
Anyway thanks for the support.Your plugin works good but the mistake is due to leverage browsing caching.I have flushed the cache it isn't showing the combined js but while testing my site using gtmetrix shows a .js file instead of bunch of files.Thanks for the support
