### ISSUE TITLE
Could it be that minit finds its js?

### ISSUE THREAD

**Issue by szepeviktor** [kasparsd/minit#38]
```js
/* TOC:
 - minit-6eaa7fd0bd3f5cd86377f82510bfed97
*/

/* Minit: http://chrisdry.wp/wp-content/uploads/minit/6eaa7fd0bd3f5cd86377f82510bfed97.js */
/* TOC:
 - jquery-core
 - jquery-migrate
 - jquery
 - aqpb-view-js
 - comment-reply
 - gravity_plug_modernizr
 - gravity_plug_easing
```

**Comment by szepeviktor** [comment]
It is a very nifty case:
script's src contained `....js?rev=1.2.3` revision number, it's version was not set.
`// Skip if the file is not hosted locally` skipped the script but later it got into `add()` JS call.
Could you check for `?` in the script's name and handle accordingly?

**Comment by szepeviktor** [comment]
Now I think that even without `?` in the url minit minifies it's own generated JS.

**Comment by szepeviktor** [comment]
I think the header's combined JS gets minified again in the footer.

**Comment by szepeviktor** [comment]
As I see if the combined script exists then it does not get `async_print`-ed.

**Comment by szepeviktor** [comment]
Could it be that `if ( ! $script_relative_path ) {` should be `if ( $script_relative_path ) {`?

**Comment by kasparsd** [comment]
@szepeviktor I have also experienced the issue you described, however it is not related to the external scripts. I am not sure what causes it.

**Comment by szepeviktor** [comment]
I think the `!` in `if`.

**Comment by szepeviktor** [comment]
Oh! I see

> Print external scripts asynchronously in the footer

So locally hosted scripts are loaded synchronously.

**Comment by szepeviktor** [comment]
I am trying to reach PageSpeed 100 thus loading everything async.

**Comment by szepeviktor** [comment]
Could it be that the combined script from the header get re-minit-ed in the footer?

**Comment by kasparsd** [comment]
@szepeviktor It shouldn't because Minit keeps track of scripts that have been combined and excludes them from being "Minited" again:

https://github.com/kasparsd/minit/blob/master/minit.php#L169

**Comment by szepeviktor** [comment]
Thank you! I am still in the *understanding* phase.
Would you mind if I put together a PR with only comments?

**Comment by szepeviktor** [comment]
@kasparsd I think I've found the reason.
In the first go scripts registered in the header are minited, then footer scripts.
At the next page load these two minited scripts are minited again into one.

Are you planning to work on it?

**Comment by kasparsd** [comment]
> In the first go scripts registered in the header are minited, then footer scripts.
> At the next page load these two minited scripts are minited again into one.

Exactly, @szepeviktor!

Minit captures all instances of `print_scripts_array` and creates the Minit version for the files enqueued until _that_ point.

The solution is to do the Minit process right before `wp_print_footer_scripts` and use `print_scripts_array` only to capture the registered scripts.

**Comment by szepeviktor** [comment]
@kasparsd Could you implement that?

**Comment by kasparsd** [comment]
@szepeviktor Could you test the `feature/restructure` branch https://github.com/kasparsd/minit/tree/feature/restructure and let me know if it fixes the issue.

**Comment by szepeviktor** [comment]
I consider this to be solved.
