### ISSUE TITLE
URL normalization

### ISSUE THREAD

**Issue by szepeviktor** [kasparsd/minit#40]
How could CSS `url()`-s be normalized?

`http://chrisdry.wp/wp-content/themes/scribe/css/../fonts/Pe-icon-7-stroke.eot`

**Comment by kasparsd** [comment]
@szepeviktor I tried looking into this and couldn't find a suitable solution. All ideas are welcome.

**Comment by szepeviktor** [comment]
Please consider including https://github.com/glenscott/url-normalizer/blob/master/src/URL/Normalizer.php

**Comment by kasparsd** [comment]
Here is a basic method for normalizing any path without any regex https://gist.github.com/kasparsd/ad25a824506e99b0a8cf

**Comment by szepeviktor** [comment]
Have you taken a look at the above link what other parts are normalized?
E.g. scheme+domain with capitals

**Comment by kasparsd** [comment]
@szepeviktor Yes, I did have a look at the script above and it does a lot of things. I haven't received a single support request where the existing relative path approach has failed. I have decided to not implement any kind of normalization for now.

**Comment by szepeviktor** [comment]
@kasparsd OK, I see your point.
Could you make normalization possible with a hook in resolve_urls()?

**Comment by kasparsd** [comment]
> Could you make normalization possible with a hook in resolve_urls()?

@szepeviktor The relative paths are returned in the regex matches and we need to use a callback to normalize those values, which again would add some overhead. Not sure on what the best approach is.

Thanks for all your help and suggestions!
