### ISSUE TITLE
Conditional files aren't ignored

### ISSUE THREAD

**Issue by dimadin** [kasparsd/minit#42]
Minit doesn't ignore conditional files added via [wp_style_add_data](https://developer.wordpress.org/reference/functions/wp_style_add_data/) and [wp_script_add_data](https://developer.wordpress.org/reference/functions/wp_script_add_data/), so it means all files are included, like for default theme, Twenty Fifteen.

If we exclude, for example, those styles, Minit file is included after them, not before, as they depend on master style.

**Comment by kasparsd** [comment]
Indeed. We should take special care with the following extra attributes:

- `conditional` string Comments for IE 6, lte IE 7 etc.
- `rtl` bool|string To declare an RTL stylesheet.
- `suffix` string Optional suffix, used in combination with RTL.
- `alt` bool For rel=”alternate stylesheet”.
- `title` string For preferred/alternate stylesheets.

**Comment by kasparsd** [comment]
This has been fixed in [1.4.0](https://github.com/kasparsd/minit/releases/tag/1.4.0):

https://github.com/kasparsd/minit/blob/7849b353b096fe89dad4e8f2d949f82ddd3e99ba/src/minit-js.php#L71-L90
