### ISSUE TITLE
breaks the whole site

### ISSUE THREAD

**Issue by nandoptg** [kasparsd/minit#44]
My site CSS breaks when I enable this...  Not sure why...  site: idoketo.com

**Comment by szepeviktor** [comment]
Try to look at the minited CSS' TOC.

You have a big typo: `forces your body to use fat for energy resulting in weightlEss.`

**Comment by nandoptg** [comment]
typo fixed! thanks.

whats minited CSS' TOC?

**Comment by szepeviktor** [comment]
The is a Table Of Contents at the top of CSS that is created by minit.

**Comment by szepeviktor** [comment]
Check you currently included CSS files one-by-one.

**Comment by nandoptg** [comment]
will do, thanks

**Comment by kasparsd** [comment]
This is related to the particular implementation so I'm closing the issue.
