### ISSUE TITLE
jQuery not defined when plugin activated

### ISSUE THREAD

**Issue by 1BJK903** [kasparsd/minit#56]
Hi Kaspar,

First of all: great work man, This is by far the best plugin to combine files. Great work!

I have a problem though.. I am using Ajaxy Live Search plugin, but that one does not work anymore since I activated your plugin. I checked the console and it says (two times): ReferenceError: jQuery is not defined

Is there a way we can fix this? 

PS: I also noticed that the CSS does not minify. Do we have do this manually?

**Comment by kasparsd** [comment]
I'm not sure why the particular plugin doesn't work. Can you please try the latest beta version of the 0.3 release https://github.com/kasparsd/minit/releases

Minit doesn't do any kind of minifaction by default. You'll need to use a filter for that, see https://bjornjohansen.no/wordpress-minify

**Comment by 1BJK903** [comment]
Nope...

**Comment by szepeviktor** [comment]
@1BJK903 And https://github.com/kasparsd/minit/issues/53

**Comment by szepeviktor** [comment]
If a WP plugin does script printing (`echo "<script> ..."` instead of wp_enqueue_script) moving minited script to the bottom triggers `jQuery is not defined`

**Comment by 1BJK903** [comment]
@szepeviktor, so you are stating that it's the plugin who is not correctly defined and should be changed instead of Minit?

**Comment by szepeviktor** [comment]
Yes. I suspect script printing.

**Comment by kasparsd** [comment]
@1BJK903 @szepeviktor It appears that the "Ajaxy Live Search" plugin is doing everything correctly, see http://plugins.svn.wordpress.org/ajaxy-search-form/trunk/sf.php

I'm not sure why it would fail. Unfortunately I don't have the time to debug it.

**Comment by szepeviktor** [comment]
Here is the script printing: https://plugins.trac.wordpress.org/browser/ajaxy-search-form/trunk/sf.php#L1104

**Comment by kasparsd** [comment]
Oh, great find @szepeviktor! That confirms it.
