### ISSUE TITLE
uploads dir on remote server

### ISSUE THREAD

**Issue by kaalis** [kasparsd/minit#63]
I have a dev environment website on localhost that serves images from uploads directory.
`upload_url_path = 'http://whatever.com/wp-content/uploads'`

When opening localhost/whatever/ files get cached on localhost, but webpage tries to serve them from whatever.com/wp-content/uploads/minit/ where they don't exist (not a surprise).

Quick and dirty fix before using options like siteurl or home options.
`$combined_file_url = sprintf( '%s/minit/%s.%s', 'http://localhost/whatever/wp-content/uploads', $cache_ver, $this->extension );`

**Comment by szepeviktor** [comment]
Try a rule in your dev webserver's config instead of modifying `upload_url_path`:
```apache
RewriteCond "%{REQUEST_FILENAME}" !-f
RewriteRule "whatever/wp-content/uploads/(.*)$" "http://whatever.com/wp-content/uploads/$1" [R=permanent,L]
```

**Comment by kasparsd** [comment]
Closing as this is not a very common use case.
