### ISSUE TITLE
@import ??

### ISSUE THREAD

**Issue by sidati** [kasparsd/minit#65]
Hello @kasparsd,

As we all know some stylesheets has `@import` functions, and we also know that `@import` works only if its on top, for the moment MINIT doesn't move `@import` functions to the beginning of the minified file.
**BUT** it will better if MINIT, just replace the `@import` with the content from the `@imported` file.

by the way thanks for the great plugin ;),
Sidati

**Comment by kasparsd** [comment]
Thanks for the suggestion @sidati! I think it's a plugin territory. One could use the `minit-content-css` filter to do that.

**Comment by szepeviktor** [comment]
@sidati See https://github.com/markoheijnen/Minit-Pro/blob/master/minit-pro.php#L75

**Comment by sidati** [comment]
@kasparsd , but what is the deal of keeping `@import` if it dosent work ?? You must at least move it to the beginning of content.

**Comment by szepeviktor** [comment]
Maybe a decent CSS file has no @import-s.

**Comment by kasparsd** [comment]
@sidati I personally don't use `@import` so if you could create a pull request, I would have a look.

**Comment by sidati** [comment]
@kasparsd,
OK, and please take look at line `564` (latest stable version), cause there is no such action `minit-cache-purge-delete`, maybe you meant : `minit-cache-purged` in `548`.

**Comment by kasparsd** [comment]
@sidati Minit won't delete old cache files under any circumstances so we offer a sample action that can be used by other plugins to do that instead.

**Comment by sidati** [comment]
@kasparsd got it

**Comment by sidati** [comment]
Take a look when you have a time :
https://github.com/sidati/minit/commit/3f0f618746f3a172b53582f24405977e8517a229
