### ISSUE TITLE
Minit compatibility in load balanced environment

### ISSUE THREAD

**Issue by cjmaio** [kasparsd/minit#68]
I am using Minit on a WordPress environment that is a bit more complex than a standard one. There are 3 WordPress servers that use rsync to sync the WordPress filesystem, and a master - slave database setup.

Is there any reason that Minit would only work on one server, and not the others? 

I've verified that the cached CSS / JS files are present on all of the servers. However, testing the site loading on each individual server, it seems to only load on the one that the cache files were first created on.

Any ideas off the top of your head?

**Comment by kasparsd** [comment]
@cjmaio Are they all connecting to the same DB? The cache purge key is stored [in an option](https://github.com/kasparsd/minit/blob/master/minit.php#L98). Or it could be failing at one of the [`file_exists()` checks](https://github.com/kasparsd/minit/blob/master/minit.php#L125).

**Comment by cjmaio** [comment]
They are all connecting to the same DB, but it’s replicated so there may be a delay. The files should all exist on the servers.

Is it possible that multiple options are being set confusing the plugin? For example, if it loaded on two of the web nodes at relatively the same time, creating two options? I am going to try and look through it today to see if I can see where it may be failing, but those are two good places to start.

**Comment by cjmaio** [comment]
I actually figured out this issue, and sorry, it had nothing to do with the plugin. Turns out my syncing was not working across the servers, and the transient was getting stuck in memcached. So even though the files didn't exist, Minit didn't try to create a new combined CSS file.
