### ISSUE TITLE
Allow filter for CDN absolute URL in CSS

### ISSUE THREAD

**Issue by unclhos** [kasparsd/minit#70]
How can I use CDN for assets in CSS? Is it possible to filter the url without going in a modifying the urls by hand?

**Comment by LQ2-apostrophe** [comment]
Hello!

For this, I have written a seperate plugin as an addon. Check it here: https://github.com/LQ2-apostrophe/minit-cdn

**Comment by szepeviktor** [comment]
Do you mean have your CDN serve the minited CSS file?

You could
- hook [minit-url-css](https://github.com/kasparsd/minit/blob/6e1e7de7934c15c5fcf62cd56514131e563f92cb/include/minit-assets.php#L130-L143)
- get protocol and host by `wp_upload_dir()`
- replace them with CDN protocol and CDN host
- return it

**Comment by kasparsd** [comment]
@unclhos I would probably use the `minit-content-css` filter (not tested):

```
add_filter( 'minit-content-css', function( $css ) {
	return str_replace(
		'//example.com',
		'//cdn.example.com',
		$css
	);
} );
```
