### ISSUE TITLE
inline scripts loading before the minified script

### ISSUE THREAD

**Issue by lineshjose** [kasparsd/minit#72]
Hi,
I really like your plugin. 

A lots of inline script are loading before the minified script, that included jquery, in footer so I getting "**jQuery is not defined**" error, because of this some inline script not working.

How can i fix this issue

**Comment by kasparsd** [comment]
@lineshjose you need to exclude `jquery` from being processed by Minit:

```
add_filter( 'minit-exclude-js', function( $handles ) {
    $exclude = array(
        'jquery',
    );

    return array_merge( $handles, $exclude );
} );
```

**Comment by lineshjose** [comment]
Thanks. I've excluded jquery from Minit and it loading in header now and everything is working :)

But it lowered the google's pagespeed  score because of "render-blocking JavaScript".
Is there any way to load jquery in footer before the all other scripts?

**Comment by kasparsd** [comment]
Minit already does that but your page is probably calling jQuery somewhere before the footer scripts are loaded. You should remove all the inline scripts that are called before Minit instead.

**Comment by aneeshjajodia** [comment]
It still is giving me the error. @kasparsd 

Could you help me out?
