### ISSUE TITLE
Too many connections from this host

### ISSUE THREAD

**Issue by JosiahCarberry** [kasparsd/minit#73]
Sometimes, my apache error log shows errors similar to:

Rejected, too many connections from this host. (vhost:mysite.com uri:/wp-content/uploads/minit/72d34452630775c48af54770509f11d0.js current:33 limit:30

Is this due to the fact of have put numerous scripts together into one, as managed by minit?

**Comment by kasparsd** [comment]
I'm not sure what that limit is. It shouldn't have anything to do with the contents of the script or the plugin.
