### ISSUE TITLE
ReferenceError: Can't find variable: jQuery

### ISSUE THREAD

**Issue by aneeshjajodia** [kasparsd/minit#74]
Its giving me these kind of errors:

<img width="1440" alt="screenshot 2016-06-25 05 19 03" src="https://cloud.githubusercontent.com/assets/1062704/16353190/5a458326-3a94-11e6-8a23-27e275accd2f.png">

Also, causing issues in loading my product page picture, which in-turn is creating plenty of other problems.

<img width="783" alt="screenshot 2016-06-25 05 19 54" src="https://cloud.githubusercontent.com/assets/1062704/16353196/76b24850-3a94-11e6-857f-0ff6b1d8dece.png">

Can someone help me through this?

**Comment by szepeviktor** [comment]
You might have inline jQuery scripts.
Minit moved jQuery to the bottom and it gave errors to you.
See #72

**Comment by aneeshjajodia** [comment]
@szepeviktor Done that. Still the error is persisting.
<img width="1440" alt="screenshot 2016-06-25 05 27 11" src="https://cloud.githubusercontent.com/assets/1062704/16353259/7a97962c-3a95-11e6-8a47-c2c2fc3b86e4.png">

The image above also consists of the link, i.e. https://www.lomdi.in/shop/taxi-kites-for-iphone-6-iphone-6s/.

Can you help me through it? I would be really glad on that.

Best.

**Comment by szepeviktor** [comment]
See your monit-ed JS: /store/wp-content/uploads/minit/6d44b1c7f6aaaf9d911908cf1cf992a8.js
jQuery is still in it.
Please add the code in https://github.com/kasparsd/minit/issues/72#issuecomment-228000073 to your theme.

**Comment by aneeshjajodia** [comment]
Hey @szepeviktor !

Really glad for your help. I did add it to my functions.php of my child theme that I have been using. I tried but still I get the same error. I'm using the **master version**.
<img width="564" alt="screenshot 2016-06-25 06 05 01" src="https://cloud.githubusercontent.com/assets/1062704/16353623/cbce135e-3a9a-11e6-940f-955457bda0b4.png">

**Comment by szepeviktor** [comment]
Have you cleared minit cache?

**Comment by aneeshjajodia** [comment]
@szepeviktor Yes I did. Multiple times 😕

**Comment by szepeviktor** [comment]
You find the **handles** in https://www.lomdi.in/store/wp-content/uploads/minit/6d44b1c7f6aaaf9d911908cf1cf992a8.js

`jquery-core` and `jquery-migrate` (other could be necessary for your inline scripts)

**Comment by aneeshjajodia** [comment]
@szepeviktor I did add *jquery-core* to the exclude list as well. It removed the errors, but nothing loads up now. 
<img width="1440" alt="screenshot 2016-06-25 06 19 04" src="https://cloud.githubusercontent.com/assets/1062704/16353732/b9f666de-3a9c-11e6-8303-a81dbef7744d.png">

**Comment by szepeviktor** [comment]
I am sorry to say but purchased themes are pool quality.
Minit may not work with all themes.

Your theme' inline scripts may need additional jquery-* scripts.
Try comparing the page's source with and without minit.
I've written Frontend Debugger plugin for that.

**Comment by aneeshjajodia** [comment]
Would be delighted if you could link me to that.

..
Anish Jajodia

On 25 June 2016 at 06:23:47, Viktor Szépe (notifications@github.com) wrote:

I am sorry to say but purchased themes are pool quality.
Minit may not work with all themes.

Your theme' inline scripts may need additional jquery-* scripts.
Try comparing the page's source with and without minit.
I've written Frontend Debugger plugin for that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kasparsd/minit/issues/74#issuecomment-228497410>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABA3MNPk2L46tvVKyTMsXOI7hJRb3oawks5qPHwSgaJpZM4I-NY2>
.

**Comment by szepeviktor** [comment]
Try Google search!

**Comment by aneeshjajodia** [comment]
Cool enough.

Thanks man.

..
Anish Jajodia

On 25 June 2016 at 06:24:49, Anish Jajodia (me@aneesh.me) wrote:

Would be delighted if you could link me to that.

..
Anish Jajodia

On 25 June 2016 at 06:23:47, Viktor Szépe (notifications@github.com) wrote:

I am sorry to say but purchased themes are pool quality.
Minit may not work with all themes.

Your theme' inline scripts may need additional jquery-* scripts.
Try comparing the page's source with and without minit.
I've written Frontend Debugger plugin for that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kasparsd/minit/issues/74#issuecomment-228497410>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABA3MNPk2L46tvVKyTMsXOI7hJRb3oawks5qPHwSgaJpZM4I-NY2>
.

**Comment by kasparsd** [comment]
@aneeshjajodia Unfortunately we can't help you with specific implementation issues.
