### ISSUE TITLE
Minifying the end JS file

### ISSUE THREAD

**Issue by aneeshjajodia** [kasparsd/minit#75]
Hello,

I would like to minify the end cache'd js file as well.

Can someone help me through that?

**Comment by kasparsd** [comment]
You need to use the `minit-content-js` and `minit-content-css` [filters](https://github.com/kasparsd/minit/blob/7deaf0d47c5e33208726276b1ff53f0c595ab98b/minit.php#L157).

**Comment by aneeshjajodia** [comment]
Hello,

I'm very sorry for opening the thread again, please can you guide me a little more, on the same?

**Comment by aneeshjajodia** [comment]
@kasparsd Really sorry for being buggy, but unable to understand.

**Comment by szepeviktor** [comment]
Try https://github.com/markoheijnen/Minit-Pro

**Comment by aneeshjajodia** [comment]
@szepeviktor So minit and minitpro both should be enabled?

**Comment by szepeviktor** [comment]
Yes. I think Minit Pro is for the feature/restructure.
But please understand this is not a support form.
Find a developer to guide you throught.
All the best!

**Comment by aneeshjajodia** [comment]
@szepeviktor I completely understand the same. I would just wish to minify the end js file that is obtained after concat.
