### ISSUE TITLE
video embed

### ISSUE THREAD

**Issue by zocoloco** [kasparsd/minit#76]
I've embedded a vimeo video. When minit is enabled, the video won't display (no javascript error). When I disable minit, the video displays. Suggestions?

**Comment by GermontZ** [comment]
An idea! consider excluding from minification .css or .js files that contain in their names _mediaelement_. Search in wordpress folders.

**Comment by kasparsd** [comment]
Thanks for the suggestions @GermontZ! Unfortunately, we're unable to assist with debugging implementation issues @zocoloco.
