### ISSUE TITLE
Minification plugins

### ISSUE THREAD

**Issue by ryanhellyer** [kasparsd/minit#78]
Is there a recommended minification plugin for use with Minit?

I tried Marko's Minit Pro plugin, but it seems to be a bit too aggressive, and was breaking the JS unfortunately:
https://github.com/markoheijnen/Minit-Pro

EDIT: I closed this briefly because I thought my Minit Pro problem was my fault, but it seems not.

**Comment by bjornjohansen** [comment]
I suppose this one still works: https://github.com/bjornjohansen/minit-min

**Comment by szepeviktor** [comment]
@ryanhellyer Do you mean [JSqueeze](https://github.com/markoheijnen/Minit-Pro/blob/master/lib/JSqueeze.php) has a bug? https://github.com/tchwork/jsqueeze/issues/new

**Comment by markoheijnen** [comment]
I changed the code on one site a bit to prevent that breakage. I believe you are seeing that with the embed js file.

**Comment by szepeviktor** [comment]
@ryanhellyer I see your 404 for the minited JS.
Please see https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/404-adaptive.php

**Comment by ryanhellyer** [comment]
@bjornjohansen Nope, that doesn't seem to be working. I'll try to fix it though.

**Comment by ryanhellyer** [comment]
Thanks @markoheijnen :)

**Comment by ryanhellyer** [comment]
@szepeviktor I'm not sure. I just tried the Minit Pro plugin and found it broke my JS, so wanted to check here in case @kasparsd or others had a specific plugin they recommended over the others.

**Comment by ryanhellyer** [comment]
@bjornjohansen Yep, that worked! I'll use that in the interim, until @markoheijnen can hopefully iron out whatever the problem is with Minit Pro.

(I originally commented here saying Minit min wasn't working, but I was just being stupid and forgot to purge the cache before testing it)

**Comment by ryanhellyer** [comment]
@szepeviktor Thanks for noticing that 404 error on my root site. I'm not sure why it's doing that, but I can see it's using a URL with `/files/` in it, which doesn't make sense since it's the root of a multisite install, and so should use `/wp-content/uploads/`.

It seems to be working fine on another multisite network I'm using it on though.

**Comment by szepeviktor** [comment]
There may be a `define( 'WP_CONTENT_URL', 'blabla/files' );` in your wp-config.

**Comment by ryanhellyer** [comment]
Nope, there is not.

**Comment by szepeviktor** [comment]
Oh! It must be a multiste.

**Comment by ryanhellyer** [comment]
Yes, it is definitely a multisite. I don't think this is bug is related to Minit though. I think it's a general problem with that root site.

**Comment by ryanhellyer** [comment]
@szepeviktor It turned out the uploads on that site never worked because I hadn't configured the /files/ URLs in Nginx. Thanks spotting it :) You are also the first person I've ever heard of visiting that root domain.

**Comment by szepeviktor** [comment]
It is easy to find these thing as my main activity is [proactive maintenance](https://github.com/szepeviktor/debian-server-tools/blob/master/CV.md) of HTTP-based services.

**Comment by kasparsd** [comment]
Thank you everyone for the suggestions! I'm closing this for now.
