### ISSUE TITLE
Simple way to exclude certain JS/CSS files?

### ISSUE THREAD

**Issue by mhote** [kasparsd/minit#79]
Hi, for us 'amateur' programmers here, is there a simple way to edit this plugin or exclude certain CSS files, which aren't working properly when combined (which is working very well by the way!)

Eg. For example if trying to exclude, the below, how we would do that?
https://domain.com/cdn-cgi/nexp/dok3v=165.js

thanks

**Comment by kasparsd** [comment]
Check out the [example here](https://github.com/kasparsd/minit/blob/master/include/helpers.php#L57-L68):

```
add_filter( 'minit-exclude-js', 'minit_exclude_defaults' );
function minit_exclude_defaults( $exclude ) {
	$exclude[] = 'the-handle-of-the-script'; // the first argument of wp_enqueue_script()
	return $exclude;
}
```
