### ISSUE TITLE
Existing plugins

### ISSUE THREAD

**Issue by ryanhellyer** [kasparsd/minit#82]
I'm thinking it may be useful to add a list of links to existing extension plugins to the README.md file.

In particular, plugins (or code for) the following I think would be useful:
- Auto-purge Cron
- Minification
- CDN URLs

I'm aware of existing code for minification and CDN URLs, but not Cron purging.

**Comment by ryanhellyer** [comment]
Since I couldn't find an auto purge plugin, I made one ... https://github.com/ryanhellyer/minit-cron-purge

**Comment by ryanhellyer** [comment]
And here's another one for disabling Minit when logged in.
https://github.com/ryanhellyer/minit-disable-for-logged-in-users

This was causing me some headaches with Beaver Builder. I think Beaver Builder was dynamically building JS and CSS files on the fly, and glitching out when Minit tried to serve the old concatenated file.

**Comment by kasparsd** [comment]
Thank @ryanhellyer! Would you like to open a pull request with the updated `readme.md`?

Secondly, I was wondering what is the use case for the Minit Cron Purge plugin? Is that mainly for keeping the `minit` cache folder clean?

**Comment by kasparsd** [comment]
@ryanhellyer Note that with static page caching you might end up with 404s on the those asset files that are still referenced in the HTML output.

**Comment by szepeviktor** [comment]
A wiki page page would be more suitable as users may edit it.

**Comment by kasparsd** [comment]
@szepeviktor That is a great suggestion. We could link to that wiki page from the readme then.

**Comment by ryanhellyer** [comment]
@kasparsd Yeah, I'm experiencing that darned static page caching problem ;)

My reasoning, was that I'm having some issues with the cache not being purged when it should be. Some plugins don't update their version numbers, and so the cache isn't purging when intended :/ But it is of course causing the issue you mentioned, which is problematic.

**Comment by ryanhellyer** [comment]
@kasparsd I suspect I'm meant to run `Minit_Plugin::cache_bump()` as you mentioned in another ticket instead of purging the whole cache. So I may refactor that plugin if that turns out to be the case.

**Comment by kasparsd** [comment]
Fixed in #91.

**Comment by szepeviktor** [comment]
There are several minification addons but Minit-Pro is superior.

**Comment by kasparsd** [comment]
@szepeviktor I would like to list them all so a Wiki page would be awesome like you suggested. We can then change the readme to link to that Wiki page instead.

**Comment by ryanhellyer** [comment]
The Wiki page is here, in case anyone missed it:
https://github.com/kasparsd/minit/wiki/Minit-Extensions
