### ISSUE TITLE
Add instructions to bump version numbers to trigger cache purge

### ISSUE THREAD

**Issue by ryanhellyer** [kasparsd/minit#83]
I didn't find it obvious that you need to bump the wp_enqueue version number to trigger a cache purge. I think this should be added to the README.md documentation for dummies like myself who don't realise how the plugin works.

**Comment by kasparsd** [comment]
Thanks @ryanhellyer, that is a good suggestion. Would you like to send a pull request?

The alternative is to bump the global cache version in the admin or by calling `Minit_Plugin::cache_bump()`.

**Comment by szepeviktor** [comment]
@kasparsd Related to #114

**Comment by kasparsd** [comment]
This has been [added to readme now](https://github.com/kasparsd/minit/blame/d21f304e6047a819917d8afb0a8d270ba2999b56/readme.md#L17).
