### ISSUE TITLE
Not compatible with Simple Custom CSS

### ISSUE THREAD

**Issue by JaddyAhmed** [kasparsd/minit#89]
I tried to use Minit on one of my client's site. I am using Simple Custom CSS (https://wordpress.org/plugins/simple-custom-css/) to add custom css.

I use Autoptimize but testing Minit and see if I can replace Autoptimize. SCS works like a charm with Autoptimize but Minit somehow skips the custom CSS.

**Comment by kasparsd** [comment]
> Minit somehow skips the custom CSS

@JaddyAhmed Could you please describe that?

That plugin loads the whole WP and then replaces the output with the CSS only, see https://plugins.svn.wordpress.org/simple-custom-css/trunk/includes/public.php
