### ISSUE TITLE
Exclude JS

### ISSUE THREAD

**Issue by charliepp** [kasparsd/minit#90]
Hey,
just wanted to ask if you could help me excluding some JS that went broke after adding your plugin.

(btw. this is one of the best plugins ive ever used with wordpress! went from 8 css and 7 js to 1 css and 1js and speedscores as well as overal load speed improved like a charm)

The problem i have is that the JS i want to exclude doesnt seem to have an ID adressed to it.
`<script type='text/javascript' src='http://www.mypage.de/wp-content/plugins/gravityforms/js/gravityforms.min.js?ver=2.0.7.13' defer onload=''></script>`
html code looks like this.

There are 4 gravityforms js scripts that i probably need to exclude to make my form work again:

```
gravityforms/js/jquery.json.js?ver=2.0.7.13
gravityforms/js/gravityforms.min.js?ver=2.0.7.13
gravityforms/js/conditional_logic.min.js?ver=2.0.7.13
gravityforms/js/placeholders.jquery.min.js?ver=2.0.7.13
```

Is there any way to exclude those scripts even though they dont have an id adressed to them?

One further question (shame on my for that one) i assume i have to put the exclude filter inside my active theme functions.php - is that corect?

Hope you can help me out,
Cheers
Charliepp

**Comment by kasparsd** [comment]
@charliepp I'm sorry but I can't provide implementation support.

Scripts without IDs are added using non-standard methods and shouldn't be included in the combined Minit file.

**Comment by kasparsd** [comment]
> i assume i have to put the exclude filter inside my active theme functions.php - is that corect?

Yes, that is correct.

**Comment by kasparsd** [comment]
Finally, it looks like you have another script doing some kind of JS/CSS optimization thing because I see the `defer onload=''` attributes on the script tags which are not there by default.

**Comment by charliepp** [comment]
kasparsd i thank you for that fast and satisfying answer.
Great job on that plugin anyways, there are a whole bunch of sites on which i am able to use it.
Thanks!

**Comment by szepeviktor** [comment]
If you have a development version you may use this debugger:
https://wordpress.org/plugins/frontend-debugger/
By adding the `?remove-scripts` GET parameter all WordPress-registered scripts will transform into a comment, this way you may inspect output easily.
Use the *Highlight* button on the control panel: https://wordpress.org/plugins/frontend-debugger/screenshots/
